
learn:
  log_stat: False
  epochs: 150
  batch_size: 450
  lr: 1e-4
  save_model: True
  loss: 'mse'

transformer_arch:
  enc_layer: 2
  dec_layer: 1
  n_head: 4
  d_model: 128
  dropout: 0.1
  factor: 3

np:
  clip_gradients: True
  latent_obs_dim: 30  #orig


data_reader:
  context_size: 49
  pred_len: 1
  standardize: True



